Create an array of 10 zeros and ones

In [3]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of even integers from 10 to 50

In [7]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

Create an Identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a matrix with the values changing from 0 to 8

In [9]:
data=np.arange(0,9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Use NumPy to create a random number between 0 to 1

In [10]:
np.random.rand()

0.2296884720819966

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
np.random.randn(25)

array([-0.19682567, -0.52103876, -0.65726958, -0.37134931,  0.90703008,
       -0.78935324, -0.93834158, -0.632905  ,  0.52429809,  0.1618846 ,
        0.16240089, -2.81486863, -1.86135462,  0.15060823,  1.44896976,
        0.36150949, -0.39350953,  0.45193016,  1.24374988,  0.76769417,
        2.32378117,  0.60258008, -0.67804978,  0.21063475,  0.39769768])

Create a 10x10 with values changing from 0.01 to 1.00

In [12]:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
matrix


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create an array of 20 linearly spaced points between 0 and 1

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Create a 10x10 with values changing from 0.01 to 1.00 using linspace 

In [14]:
matrix = np.linspace(0.01, 1.00, num=100).reshape(10, 10)
matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [15]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Print ([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Print 20 from the matrix

In [17]:
arr[3,4]

20

Print ([[ 2],
       [ 7],
       [12]])

In [18]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

Print ([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Print sum of all the array elements

In [20]:
arr.sum()

325

Print the standard deviation

In [21]:
arr.std()

7.211102550927978

Print the sum of columns in the matrix

In [22]:
column_sums = np.sum(arr, axis=0)
column_sums

array([55, 60, 65, 70, 75])

Print the sum of rows in the matrix

In [23]:
row_sums = np.sum(arr, axis=1)
row_sums

array([ 15,  40,  65,  90, 115])